# Generated by Django 5.2 on 2025-04-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='climate_zone',
            field=models.CharField(choices=[('tropical', 'Tropical'), ('subtropical', 'Subtropical'), ('temperate', 'Temperate'), ('arid', 'Arid')], default='tropical', max_length=20, verbose_name='Climate Zone'),
        ),
        migrations.AddField(
            model_name='crop',
            name='growing_season',
            field=models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('monsoon', 'Monsoon'), ('all', 'All Season')], default='all', max_length=20, verbose_name='Growing Season'),
        ),
        migrations.AddField(
            model_name='crop',
            name='growth_period',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Growth Period'),
        ),
        migrations.AddField(
            model_name='crop',
            name='irrigation_method',
            field=models.CharField(choices=[('drip', 'Drip'), ('sprinkler', 'Sprinkler'), ('flood', 'Flood'), ('rainfed', 'Rainfed')], default='rainfed', max_length=20, verbose_name='Irrigation Method'),
        ),
        migrations.AddField(
            model_name='crop',
            name='market_demand',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Market Demand'),
        ),
        migrations.AddField(
            model_name='crop',
            name='market_preference',
            field=models.CharField(choices=[('local', 'Local Market'), ('export', 'Export Market'), ('both', 'Both')], default='local', max_length=20, verbose_name='Market Preference'),
        ),
        migrations.AddField(
            model_name='crop',
            name='max_ph',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=4, verbose_name='Maximum pH'),
        ),
        migrations.AddField(
            model_name='crop',
            name='max_rainfall',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=6, verbose_name='Maximum Rainfall (mm/year)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='min_ph',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=4, verbose_name='Minimum pH'),
        ),
        migrations.AddField(
            model_name='crop',
            name='min_rainfall',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=6, verbose_name='Minimum Rainfall (mm/year)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='price_stability',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Price Stability'),
        ),
        migrations.AddField(
            model_name='crop',
            name='soil_type',
            field=models.CharField(choices=[('loamy', 'Loamy'), ('sandy', 'Sandy'), ('clay', 'Clay'), ('silt', 'Silt')], default='loamy', max_length=20, verbose_name='Soil Type'),
        ),
        migrations.AddField(
            model_name='crop',
            name='water_requirement',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Water Requirement'),
        ),
        migrations.AddField(
            model_name='crop',
            name='yield_potential',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Yield Potential'),
        ),
    ]
