# Generated by Django 5.2 on 2025-04-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_crop_climate_zone_crop_growing_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crops/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='market_preference',
            field=models.CharField(choices=[('local', 'Local Market'), ('export', 'Export Market'), ('both', 'Both')], default='both', max_length=20, verbose_name='Market Preference'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='max_ph',
            field=models.FloatField(default=7.5, verbose_name='Maximum pH'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='max_rainfall',
            field=models.FloatField(default=2000, verbose_name='Maximum Rainfall (mm/year)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='min_ph',
            field=models.FloatField(default=6.0, verbose_name='Minimum pH'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='min_rainfall',
            field=models.FloatField(default=500, verbose_name='Minimum Rainfall (mm/year)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('quintal', 'Quintal'), ('ton', 'Ton'), ('bag', 'Bag')], max_length=20, verbose_name='Unit'),
        ),
    ]
