# Generated by Django 5.0.2 on 2025-04-11 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bid Price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Is Accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='crops.crop')),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, verbose_name='Crop Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('quintal', 'Quintal'), ('ton', 'Ton'), ('bag', 'Bag')], default='kg', max_length=10, verbose_name='Unit')),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maximum Price')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demand',
                'verbose_name_plural': 'Demands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Is Accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bidding.demand')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demand Response',
                'verbose_name_plural': 'Demand Responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
